kind: pipeline
type: docker
name: integration

steps:
  - name: code_analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
      PGCONN:
        from_secret: PGCONN
    commands:
      - dotnet sonarscanner begin /k:"easv-devops_Kindergarten_Platform_AY-VL_lHEVvRW2O60FzP" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.token="$SONARSECRET" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      - dotnet build --no-incremental
      - PGCONN=$PGCONN dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"

---
kind: pipeline
type: docker
name: deliver
depends_on:
  - integration

steps:
  - name: publish api
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: .
      dockerfile: api/Dockerfile
      repo: doina1992/cd-converter-api
      tags:
        - staging


  - name: publish flutter web
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: .
      dockerfile: kindergarten_app/Dockerfile
      repo: doina1992/flutter-web-app
      tags:
        - staging