kind: pipeline
type: docker
name: integration

steps:
  - name: code_analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
      PGCONN:
        from_secret: PGCONN
    commands:
      - dotnet sonarscanner begin /k:"easv-devops_Kindergarten_Platform_AY-VL_lHEVvRW2O60FzP" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.token="$SONARSECRET" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      - dotnet build --no-incremental
      - PGCONN=$PGCONN dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"

---
kind: pipeline
type: docker
name: deliver
depends_on:
  - integration

steps:
  - name: publish api
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: .
      dockerfile: api/Dockerfile
      repo: doina1992/cd-kindergarten-api
      tags:
        - staging


  - name: publish flutter web
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      context: .
      dockerfile: kindergarten_app/Dockerfile
      repo: doina1992/cd-kindergarten-web
      tags:
        - staging


  - name: trigger update
    image: curlimages/curl
    commands:
      - "curl --fail -X GET 'http://95.111.247.237:8080/v1/update' -H 'Authorization: Bearer mytoken'"
      - sleep 30
    depends_on:
      - publish api
      - publish flutter web


  - name: update database
    image: flyway/flyway
    commands:
      - flyway migrate
        -url=jdbc:postgresql://95.111.247.237:5432/cc
        -user=user
        -password=password
        -locations=filesystem:./db/sql
    depends_on:
      - trigger update

  - name: flutter test integration
    image: ghcr.io/cirruslabs/flutter:3.19.6
    environment:
     FLUTTER_WEB: "true"
    commands:
      - apt-get update && apt-get install -y wget gnupg
      - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
      - apt-get update && apt-get install -y google-chrome-stable
      - cd kindergarten_app
      - flutter doctor --android-licenses
      - flutter doctor
      - flutter config --enable-web
      - flutter devices
      - flutter pub get
      - flutter test --platform=chrome integration_test/app_test.dart



---
  
  kind: pipeline
  type: docker
  name: deploy
  depends_on:
    - deliver
  
  steps:
    - name: release api
      image: plugins/docker
      settings:
        username:
          from_secret: DockerUsername
        password:
          from_secret: DockerPassword
        context: .
        dockerfile: api/Dockerfile
        repo: doina1992/cd-kindergarten-api
        tags:
          - prod

    - name: release web
      image: plugins/docker
      settings:
        username:
          from_secret: DockerUsername
        password:
          from_secret: DockerPassword
        context: .
        dockerfile: kindergarten_app/Dockerfile
        repo: doina1992/cd-kindergarten-web
        tags:
          - prod

    - name: trigger update
      image: curlimages/curl
      commands:
        - "curl --fail -X GET 'http://144.91.75.24:8080/v1/update' -H 'Authorization: Bearer mytoken'"
        - sleep 30
      depends_on:
        - release api
        - release web

    - name: update database
      image: flyway/flyway
      commands:
        - flyway migrate
          -url=jdbc:postgresql://144.91.75.24:5432/cc
          -user=user
          -password=password
          -locations=filesystem:./db/sql
      depends_on:
        - trigger update