services:
  frontend:
    image: doina1992/cd-kindergarten-web:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  api:
    image: doina1992/cd-kindergarten-api:prod
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"